---

- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest # noqa 403 This is a workstation playbook and updating your software to the latest versions is a good idea

- name: Install extra packages
  dnf:
    name:
    - ansible-lint
    - autofs
    - awscli
    - dnf-plugins-extras-common
    - dnf-plugins-extras-kickstart
    - dnf-plugins-extras-show-leaves # dnf leaves
    - fail2ban
    - fdupes # https://www.tecmint.com/fdupes-find-and-delete-duplicate-files-in-linux/
    - fedfind
    - figlet # ascii banner generator
    - glances # super htop
    - gnome-tweak-tool
    - htop
    - hub # https://hub.github.com/
    - inotify-tools
    - inxi
    - jq
    - letsencrypt
    # - lftp
    # - libguestfs
    # - libguestfs-tools
    # - libguestfs-tools-c
    # - libguestfs-xfs
    - libtool
    - libvirt
    - lshw
    - ncftp
    # - nfs-utils
    - ngrep
    - nmap
    - nmon
    # - pandoc # convert a markdown file to another file format
    # - pass # https://www.passwordstore.org/
    # - pssh
    - pv
    - pylint
    - pypy
    - python3-virtualenv
    # - qiv # lightwaight image viewer # https://www.linuxlinks.com/qiv/
    # - qpdf
    - ranger # https://ranger.github.io/
    # - rpm-ostree
    # - ruby
    # - ruby-irb
    # - rubygems
    - screen
    - screenfetch # google image for screenfetch
    # - setools-console # selinux
    - snapd
    # - socat # https://www.redhat.com/sysadmin/getting-started-socat
    - speedtest-cli
    - strace
    # - sysstat
    # - system-storage-manager # https://system-storage-manager.github.io/
    - task # task manager (todo) : https://www.systutorials.com/docs/linux/man/1-task/
    - terminator
    # - testdisk
    # - tlp # https://linrunner.de/tlp/index.html
    # - tlp-rdw # https://linrunner.de/tlp/usage/tlp-rdw.html
    - tmux
    - transmission-cli
    # - tuned # https://tuned-project.org/
    # - tuned-utils
    # - tuned-utils-systemtap
    - units
    - vagrant
    - vagrant-doc
    # - vagrant-libvirt
    # - vagrant-libvirt-doc
    - vim-enhanced
    # - virt-top
    - whois
    # - xbacklight
    - xclip
    # - xournal # google images for xournal
    - xsel
    state: installed

- name: Install extra fonts
  dnf:
    name:
    - adobe-source-code-pro-fonts
    - dejavu-sans-fonts
    - dejavu-sans-mono-fonts
    - dejavu-serif-fonts
    - gnu-free-fonts-common
    - gnu-free-mono-fonts
    - gnu-free-sans-fonts
    - gnu-free-serif-fonts
    - levien-inconsolata-fonts
    - liberation-fonts-common
    - liberation-mono-fonts
    - liberation-sans-fonts
    - liberation-serif-fonts
    - mozilla-fira-mono-fonts
    - msimonson-anonymouspro-fonts
    - overpass-fonts
    - terminus-fonts
    state: installed
  when: install_extra_fonts
