---

- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest # noqa 403 This is a workstation playbook and updating your software to the latest versions is a good idea

- name: Install extra packages
  dnf:
    name:
    - ansible-lint
    - autofs
    - awscli
    - dnf-plugins-extras-common
    - dnf-plugins-extras-kickstart
    - dnf-plugins-extras-show-leaves # dnf leaves
    - fail2ban
    - fdupes # https://www.tecmint.com/fdupes-find-and-delete-duplicate-files-in-linux/
    - fedfind
    - figlet # ascii banner generator
    - glances # super htop
    - gnome-tweak-tool
    - htop
    - hub # https://hub.github.com/
    - inotify-tools
    - inxi
    - iotop
    - iptraf-ng
    - jq
    - kismet
    - letsencrypt
    - lftp
    - libguestfs
    - libguestfs-tools
    - libguestfs-tools-c
    - libguestfs-xfs
    - libicns-utils
    - libmtp-examples
    - libnfs
    - libnfsidmap
    - libtool
    - libvirt
    - livecd-tools
    - liveusb-creator
    - lorax
    - lshw
    - lsscsi
    - ltrace
    - ncftp
    - nfs-utils
    - ngrep
    - nmap
    - nmon
    - pandoc
    - pass
    - patchutils
    - pavucontrol
    - pavumeter
    - pinta
    - pssh
    - pv
    - pykickstart
    - pylint
    - pyp2rpm
    - pypy
    - pytest
    - python3-firewall
    - python3-virtualenv
    - qiv
    - qpdf
    - ranger
    - recode
    - rpm-ostree
    - ruby
    - ruby-irb
    - rubygems
    - sbcl
    - scap-workbench
    - scapy
    - screen
    - screenfetch
    - setools-console
    - sg3_utils
    - smartmontools
    - snapd
    - socat
    - spec2scl
    - speedtest-cli
    - spin-kickstarts
    - strace
    - sysstat
    - system-storage-manager
    - task
    - terminator
    - testdisk
    - tlp
    - tlp-rdw
    - tmux
    - transmission-cli
    - tuned
    - tuned-utils
    - tuned-utils-systemtap
    - units
    - vagrant
    - vagrant-doc
    - vagrant-libvirt
    - vagrant-libvirt-doc
    - vim-enhanced
    - virt-top
    - whois
    - xbacklight
    - xclip
    - xfsdump
    - xournal
    - xsel
    - ykclient
    - ykpers
    state: installed

- name: Install extra fonts
  dnf:
    name:
    - adobe-source-code-pro-fonts
    - dejavu-sans-fonts
    - dejavu-sans-mono-fonts
    - dejavu-serif-fonts
    - gnu-free-fonts-common
    - gnu-free-mono-fonts
    - gnu-free-sans-fonts
    - gnu-free-serif-fonts
    - levien-inconsolata-fonts
    - liberation-fonts-common
    - liberation-mono-fonts
    - liberation-sans-fonts
    - liberation-serif-fonts
    - mozilla-fira-mono-fonts
    - msimonson-anonymouspro-fonts
    - overpass-fonts
    - terminus-fonts
    state: installed
  when: install_extra_fonts
